# Apply this with "kubectl apply -f jbtestfilter.yaml" and "kubectl apply -f jbtestfilter.yaml -n istio-system"
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: jbtestfilter
spec:
  configPatches:
  - applyTo: NETWORK_FILTER # http connection manager is a filter in Envoy
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: INSERT_BEFORE
      value:
        name: "envoy.filters.network.jb_test"
        typed_config:
          "@type": type.googleapis.com/xds.type.v3.TypedStruct
          type_url: "type.googleapis.com/envoy.tcp.jb_test.config.JBTest"
          value:
            # Config values will go in here
            prefix: "networkfilter"
  - applyTo: CLUSTER # Outbound
    match:
      context: SIDECAR_OUTBOUND # will match outbound listeners in all sidecars
    patch:
      operation: MERGE
      value:
        filters:
          - name: "envoy.filters.network.jb_test"
            typed_config:
              "@type": type.googleapis.com/xds.type.v3.TypedStruct
              type_url: "type.googleapis.com/envoy.tcp.jb_test.config.JBTest"
              value:
                # Config values will go in here
                prefix: "cluster"
  - applyTo: CLUSTER # Outbound
    match:
      context: GATEWAY # will match ingress gateway; probably also egress but I don't know how to filter that out (though it doesn't matter for Bookinfo since Bookinfo doesn't make outbound requests)
    patch:
      operation: MERGE
      value:
        typed_extension_protocol_options:
        filters:
          - name: "envoy.filters.network.jb_test"
            typed_config:
              "@type": type.googleapis.com/xds.type.v3.TypedStruct
              type_url: "type.googleapis.com/envoy.tcp.jb_test.config.JBTest"
              value:
                # Config values will go in here
                prefix: "gateway"
