# Apply this with "kubectl apply -f jbtestfilter.yaml" and "kubectl apply -f jbtestfilter.yaml -n istio-system"
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: jbtestfilter
spec:
  configPatches:
  - applyTo: NETWORK_FILTER # http connection manager is a filter in Envoy
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: INSERT_BEFORE
      value:
        name: "envoy.filters.network.tcp_compression"  # Upstream might be a bit of a misnomer but this just affects logs.
        typed_config:
          "@type": type.googleapis.com/xds.type.v3.TypedStruct
          type_url: "type.googleapis.com/envoy.tcp.compression.config.TcpCompression"
          value:
            # Config values will go in here
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.tcp_compression"
    patch:
      operation: INSERT_BEFORE
      value:
        name: "envoy.filters.network.jb_test"
        typed_config:
          "@type": type.googleapis.com/xds.type.v3.TypedStruct
          type_url: "type.googleapis.com/envoy.tcp.jb_test.config.JBTest"
          value:
            # Config values will go in here
            prefix: "networkfilter-pre"
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.tcp_compression"
    patch:
      operation: INSERT_AFTER
      value:
        name: "envoy.filters.network.jb_test"
        typed_config:
          "@type": type.googleapis.com/xds.type.v3.TypedStruct
          type_url: "type.googleapis.com/envoy.tcp.jb_test.config.JBTest"
          value:
            # Config values will go in here
            prefix: "networkfilter-post"
  - applyTo: CLUSTER # Outbound
    match:
      context: SIDECAR_OUTBOUND # will match outbound listeners in all sidecars
      # This won't apply to user-bound connections. I thought applying to all contexts (i.e. GATEWAY) would do that but doing so breaks everything.
    patch:
      operation: MERGE
      value:
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            upstream_http_protocol_options:
              auto_sni: true
            common_http_protocol_options:
              idle_timeout: 60s
            explicit_http_config:
              http2_protocol_options:
                max_concurrent_streams: 100
        filters:
          - name: "envoy.filters.network.jb_test"
            typed_config:
              "@type": type.googleapis.com/xds.type.v3.TypedStruct
              type_url: "type.googleapis.com/envoy.tcp.jb_test.config.JBTest"
              value:
                # Config values will go in here
                prefix: "cluster-pre"
          - name: "envoy.filters.network.tcp_compression"
            typed_config:
              "@type": type.googleapis.com/xds.type.v3.TypedStruct
              type_url: "type.googleapis.com/envoy.tcp.compression.config.TcpCompression"
              value:
                # Config values will go in here
          - name: "envoy.filters.network.jb_test"
            typed_config:
              "@type": type.googleapis.com/xds.type.v3.TypedStruct
              type_url: "type.googleapis.com/envoy.tcp.jb_test.config.JBTest"
              value:
                # Config values will go in here
                prefix: "cluster-post"
  - applyTo: CLUSTER # Outbound
    match:
      context: GATEWAY # will match ingress gateway; probably also egress but I don't know how to filter that out 
      # This won't apply to user-bound connections. I thought applying to all contexts (i.e. GATEWAY) would do that but doing so breaks everything.
    patch:
      operation: MERGE
      value:
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            upstream_http_protocol_options:
              auto_sni: true
            common_http_protocol_options:
              idle_timeout: 60s
            explicit_http_config:
              http2_protocol_options:
                max_concurrent_streams: 100
        filters:
          - name: "envoy.filters.network.jb_test"
            typed_config:
              "@type": type.googleapis.com/xds.type.v3.TypedStruct
              type_url: "type.googleapis.com/envoy.tcp.jb_test.config.JBTest"
              value:
                # Config values will go in here
                prefix: "gateway-pre"
          - name: "envoy.filters.network.tcp_compression"
            typed_config:
              "@type": type.googleapis.com/xds.type.v3.TypedStruct
              type_url: "type.googleapis.com/envoy.tcp.compression.config.TcpCompression"
              value:
                # Config values will go in here
          - name: "envoy.filters.network.jb_test"
            typed_config:
              "@type": type.googleapis.com/xds.type.v3.TypedStruct
              type_url: "type.googleapis.com/envoy.tcp.jb_test.config.JBTest"
              value:
                # Config values will go in here
                prefix: "gateway-post"
